### ISSUE TITLE
problem with tests- def test_fillna_rows():    

### ISSUE THREAD

**Issue by rotemorad** [sagol-python-for-neuroscientists/hw5#17]
I believe the following test is crooked
def test_fillna_rows():
    truth = np.load('tests_data/q3_fillna.npy')
    fname = 'data.json'
    q = QuestionnaireAnalysis(fname)
    q.read_data()
    _, rows = q.fill_na_with_mean()
    df.equals(truth)
----->      NameError: name 'df' is not defined

**Comment by GalBenZvi** [comment]
I believe this issue is resolved now, thanks to @HagaiHargil
